{"name": "test_sum_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testCase.test_file1.Test_001 object at 0x00000298B07E3ED0>\n\n    def test_sum_001(self):\n        a = 20\n        b = 30\n        sum = a+b\n        print(\"sum of a & b is:\" +str(sum))\n        if sum == 60:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntestCase\\test_file1.py:16: AssertionError"}, "attachments": [{"name": "stdout", "source": "ee892d80-39cd-4037-8cbd-d09ba7ab1089-attachment.txt", "type": "text/plain"}], "start": 1690734071287, "stop": 1690734071287, "uuid": "671119b6-a624-4c58-96af-472676bdb157", "historyId": "2a18788f460b5412dafdc0938abf356d", "testCaseId": "2a18788f460b5412dafdc0938abf356d", "fullName": "testCase.test_file1.Test_001#test_sum_001", "labels": [{"name": "parentSuite", "value": "testCase"}, {"name": "suite", "value": "test_file1"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "Soumya"}, {"name": "thread", "value": "13244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.test_file1"}]}